paths: 
  /api/products/:
    get:
      summary: Obtiene TODOS los productos
      tags: 
            - Products
      responses:
        "200":
          description: Operacion de consulta de productos finalizada correctamente
        "500":
          description: Operacion de consulta de productos finalizada en error  
    post:
      summary: Crea un producto
      tags: 
            - Products
      responses:
        "200":
          description: Operacion de creacion de producto finalizada correctamente
        "500":
          description: Operacion de creacion de producto finalizada en error 

  /api/products/:pid:
    get:
      summary: Obtiene el producto con id :pid
      tags: 
            - Products
      responses:
        "200":
          description: Operacion de consulta de producto finalizada correctamente
        "500":
          description: Operacion de consulta de producto finalizada en error      
    put:
      summary: Actualiza el producto con id :pid
      tags: 
            - Products
      responses:
        "200":
          description: Operacion de actualizacion de producto finalizada correctamente
        "500":
          description: Operacion de actualizacion de producto finalizada en error           
    delete:
      summary: Elimina el producto con id :pid
      tags: 
            - Products      
      responses:
        "200":
          description: Operacion de eliminacion de producto finalizada correctamente
        "500":
          description: Operacion de eliminacion de producto finalizada en error           